spring:
  profiles:
    active: dev

  application:
    name: campus-activity

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /

file:
  upload-dir: uploads

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

knife4j:
  enable: true
  setting:
    language: zh_cn
